//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Kiralik = new HashSet<Kiralik>();
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int AracId { get; set; }
        public string AracAdi { get; set; }
        public string Model { get; set; }
        public Nullable<int> EhliyetYasi { get; set; }
        public Nullable<int> MinYasSiniri { get; set; }
        public Nullable<int> GunlukSinirKM { get; set; }
        public Nullable<long> KendiAnlikKM { get; set; }
        public Nullable<bool> AirBag { get; set; }
        public Nullable<int> BagajHacmi { get; set; }
        public Nullable<int> KoltukSayisi { get; set; }
        public Nullable<decimal> GunlukKiralikFiyat { get; set; }
        public Nullable<int> SirketId { get; set; }
        public Nullable<bool> Rezerve { get; set; }
        public string Resim { get; set; }
    
        public virtual Sirket Sirket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralik> Kiralik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
