//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralik
    {
        public int KiralikId { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<System.DateTime> Alis_Tarihi { get; set; }
        public Nullable<System.DateTime> Veris_Tarihi { get; set; }
        public Nullable<long> VerilisKm { get; set; }
        public Nullable<decimal> AlinanUcret { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> YapilanKM { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
